"""changes in coupon and order model

Revision ID: 24c012ca8a60
Revises: 
Create Date: 2022-04-01 17:58:51.888623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c012ca8a60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('coupon_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('discount', sa.Integer(), nullable=True))
    op.create_foreign_key('coupon_relation', 'orders', 'coupon', ['coupon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('coupon_relation', 'orders', type_='foreignkey')
    op.drop_column('orders', 'discount')
    op.drop_column('orders', 'coupon_id')
    # ### end Alembic commands ###
