"""removed discount

Revision ID: 57a7b7b3b157
Revises: ecf5e052b7bf
Create Date: 2022-04-20 00:58:20.508533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57a7b7b3b157'
down_revision = 'ecf5e052b7bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'discount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('discount', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
