"""deleted column change

Revision ID: 88fce51ea585
Revises: fc820c0a6258
Create Date: 2022-04-06 00:59:15.954057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88fce51ea585'
down_revision = 'fc820c0a6258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
