"""added  discount

Revision ID: d131fee08cdf
Revises: 57a7b7b3b157
Create Date: 2022-04-20 00:59:09.795533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd131fee08cdf'
down_revision = '57a7b7b3b157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('discount', sa.DECIMAL(scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'discount')
    # ### end Alembic commands ###
